const PORT = process.env.PORT || 3000;
const MONGO_URL = process.env.MONGO_URL;
const CORS_ORIGIN = process.env.CORS_ORIGIN;

const NODEMAILER_HOST = process.env.NODEMAILER_HOST;
const NODEMAILER_HOST_PORT = process.env.NODEMAILER_HOST_PORT;
const NODEMAILER_AUTH_USER = process.env.NODEMAILER_AUTH_USER;
const NODEMAILER_AUTH_PASSWORD = process.env.NODEMAILER_AUTH_PASSWORD;
const CLOUDINARY_CLOUD_NAME = CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET_KEY = CLOUDINARY_API_SECRET_KEY;

export {
  PORT,
  MONGO_URL,
  CORS_ORIGIN,
  NODEMAILER_HOST,
  NODEMAILER_HOST_PORT,
  CLOUDINARY_CLOUD_NAME,
  NODEMAILER_AUTH_USER,
  CLOUDINARY_API_KEY,
  NODEMAILER_AUTH_PASSWORD,
  CLOUDINARY_API_SECRET_KEY,
};
